name: Translate locale commons json
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DeepL Translate Github Action
        uses: lyqht/deepl-translate-github-action@v2.1.0
        with:
          target_languages: ar,br,cns,fr,jp,kr,pl,ru,sw,tw
          input_file_path: public/locales/en/translation.json
          output_file_name_pattern: public/locales/{language}/translation.json
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
